import React from "react";

export default function DataFetcher() {
  const nodes = [
    {
      id: "0",
      name: "John Albert Baisa",
      course: "Bachelor Of Science In Information Techonology",
      acro: "BSIT",
      section: "BT801",
      email: "albertbaisa@gmail.com",
      ojtprogress: 100,
      ojtrequiredprogress: 486,
      ojtstartdate: new Date("2023-01-05"),
      ojtenddate: new Date("2023-05-08"),
      timeIN: "8:00",
      timeOUT: "17:00",
      companyname: "HD Homelift Solutions",
      companyaddress: "128 Congressional, Bahay Toro, Quezon City",
      companynumber: "1235-12-41",
      supervisor: "Ms. Maricris Reforma",
      contactnumber: "+63 915 293 0012",
      supervisoremail: "maricris.itymaz@gmail.com",
      designation: "IT Supervisor",
      department: "IT Department",
    },
    {
      id: "1",
      name: "Christine Fe Erjas",
      course: "Bachelor Of Science In Information Techonology",
      acro: "BSIT",
      section: "BT801",
      email: "erjaschristinefe@gmail.com",
      ojtprogress: 10,
      ojtrequiredprogress: 486,
      ojtstartdate: new Date("2023-01-05"),
      ojtenddate: new Date("2023-05-08"),
      timeIN: "8:00",
      timeOUT: "17:00",
      companyname: "HD Homelift Solutions",
      companyaddress: "128 Congressional, Bahay Toro, Quezon City",
      companynumber: "1235-12-41",
      supervisor: "Ms. Maricris Reforma",
      contactnumber: "+63 915 293 0012",
      supervisoremail: "maricris.itymaz@gmail.com",
      designation: "IT Supervisor",
      department: "IT Department",
    },
    {
      id: "1",
      name: "Christine Fe Erjas",
      course: "Bachelor Of Science In Information Techonology",
      acro: "BSIT",
      section: "BT801",
      email: "erjaschristinefe@gmail.com",
      ojtprogress: 10,
      ojtrequiredprogress: 486,
      ojtstartdate: new Date("2023-01-05"),
      ojtenddate: new Date("2023-05-08"),
      timeIN: "8:00",
      timeOUT: "17:00",
      companyname: "HD Homelift Solutions",
      companyaddress: "128 Congressional, Bahay Toro, Quezon City",
      companynumber: "1235-12-41",
      supervisor: "Ms. Maricris Reforma",
      contactnumber: "+63 915 293 0012",
      supervisoremail: "maricris.itymaz@gmail.com",
      designation: "IT Supervisor",
      department: "IT Department",
    },
    {
      id: "1",
      name: "Christine Fe Erjas",
      course: "Bachelor Of Science In Information Techonology",
      acro: "BSIT",
      section: "BT801",
      email: "erjaschristinefe@gmail.com",
      ojtprogress: 10,
      ojtrequiredprogress: 486,
      ojtstartdate: new Date("2023-01-05"),
      ojtenddate: new Date("2023-05-08"),
      timeIN: "8:00",
      timeOUT: "17:00",
      companyname: "HD Homelift Solutions",
      companyaddress: "128 Congressional, Bahay Toro, Quezon City",
      companynumber: "1235-12-41",
      supervisor: "Ms. Maricris Reforma",
      contactnumber: "+63 915 293 0012",
      supervisoremail: "maricris.itymaz@gmail.com",
      designation: "IT Supervisor",
      department: "IT Department",
    },
    {
      id: "1",
      name: "Christine Fe Erjas",
      course: "Bachelor Of Science In Information Techonology",
      acro: "BSIT",
      section: "BT801",
      email: "erjaschristinefe@gmail.com",
      ojtprogress: 10,
      ojtrequiredprogress: 486,
      ojtstartdate: new Date("2023-01-05"),
      ojtenddate: new Date("2023-05-08"),
      timeIN: "8:00",
      timeOUT: "17:00",
      companyname: "HD Homelift Solutions",
      companyaddress: "128 Congressional, Bahay Toro, Quezon City",
      companynumber: "1235-12-41",
      supervisor: "Ms. Maricris Reforma",
      contactnumber: "+63 915 293 0012",
      supervisoremail: "maricris.itymaz@gmail.com",
      designation: "IT Supervisor",
      department: "IT Department",
    },
  ];
  return nodes;
}
